//! Build script for `grepplus-embeddinggemma`.
//!
//! Does nothing unless the `embed-weights` feature is enabled. When it is,
//! it locates the quantized EmbeddingGemma GGUF and the tokenizer JSON so
//! `src/lib.rs` can bake them into the binary via `include_bytes!`, turning
//! grepplus into a single self-contained file that needs no external model.
//!
//! Resolution order for each file:
//!   1. An explicit env override (`GREPPLUS_EMBED_GGUF_PATH` /
//!      `GREPPLUS_EMBED_TOKENIZER_PATH`) — an absolute path to the file.
//!   2. A glob of the Hugging Face cache snapshots under `~/.cache/huggingface`.
//!
//! On success we emit a generated `embedded_weights_paths.rs` into `OUT_DIR`
//! that `include!`s two `include_bytes!` statements pointing at stable
//! absolute paths. The build FAILS with a clear message if a file cannot be
//! found, so a feature build never silently produces a binary with no weights.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // The default build must not depend on any of this. Only the feature
    // build bakes weights in.
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_EMBED_WEIGHTS");
    if env::var_os("CARGO_FEATURE_EMBED_WEIGHTS").is_none() {
        return;
    }

    println!("cargo:rerun-if-env-changed=GREPPLUS_EMBED_GGUF_PATH");
    println!("cargo:rerun-if-env-changed=GREPPLUS_EMBED_TOKENIZER_PATH");

    let gguf = resolve_weight(
        "GGUF",
        "GREPPLUS_EMBED_GGUF_PATH",
        &[
            "models--cduk--embeddinggemma-300m-GGUF-with-dense-modules/snapshots/*/embeddinggemma-300M-Q4_K.gguf",
        ],
    );
    let tokenizer = resolve_weight(
        "tokenizer",
        "GREPPLUS_EMBED_TOKENIZER_PATH",
        &[
            "models--google--embeddinggemma-300m-qat-q4_0-unquantized/snapshots/*/tokenizer.json",
        ],
    );

    // Re-run if the resolved files change on disk (content-addressed HF
    // blobs are stable, but an env-override path might point elsewhere).
    println!("cargo:rerun-if-changed={}", gguf.display());
    println!("cargo:rerun-if-changed={}", tokenizer.display());
    println!("cargo:rerun-if-changed=build.rs");

    // Emit a generated file with two static byte arrays. Using absolute
    // paths (rather than copying ~270MB into OUT_DIR) keeps the build fast
    // and avoids duplicating the blobs; the paths are stable because HF
    // cache blobs are content-addressed and immutable in practice.
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let generated = out_dir.join("embedded_weights_paths.rs");
    let contents = format!(
        "// @generated by build.rs — paths to the baked-in EmbeddingGemma weights.\n\
         pub(crate) static EMBEDDED_GGUF: &[u8] = include_bytes!({gguf:?});\n\
         pub(crate) static EMBEDDED_TOKENIZER: &[u8] = include_bytes!({tokenizer:?});\n",
        gguf = gguf.to_str().expect("gguf path is valid UTF-8"),
        tokenizer = tokenizer.to_str().expect("tokenizer path is valid UTF-8"),
    );
    fs::write(&generated, contents).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", generated.display());
    });
}

/// Resolve one weight file: env override first (must exist), else the first
/// match of any glob pattern under the HF cache hub dir. Panics (failing the
/// build) with an actionable message if nothing is found.
fn resolve_weight(label: &str, env_key: &str, hf_patterns: &[&str]) -> PathBuf {
    if let Some(explicit) = env::var_os(env_key) {
        let path = PathBuf::from(&explicit);
        if path.is_file() {
            return canonical(&path);
        }
        panic!(
            "embed-weights: {env_key} is set to {} but that is not a readable file. \
             Point it at the {label} file, or unset it to fall back to the HF cache.",
            path.display()
        );
    }

    let hub = hf_hub_dir();
    for pattern in hf_patterns {
        let full = hub.join(pattern);
        if let Some(found) = first_glob_match(&full) {
            return canonical(&found);
        }
    }

    panic!(
        "embed-weights: could not locate the {label} file.\n\
         Searched HF cache: {}\n\
         Patterns: {:?}\n\
         Fix: set {env_key}=/abs/path/to/{label}, or download the model into the HF cache.",
        hub.display(),
        hf_patterns,
    );
}

/// `~/.cache/huggingface/hub`, honoring `HF_HOME` / `HUGGINGFACE_HUB_CACHE`
/// the way the huggingface libraries do.
fn hf_hub_dir() -> PathBuf {
    if let Some(cache) = env::var_os("HUGGINGFACE_HUB_CACHE") {
        return PathBuf::from(cache);
    }
    if let Some(hf_home) = env::var_os("HF_HOME") {
        return PathBuf::from(hf_home).join("hub");
    }
    let home = env::var_os("HOME")
        .map(PathBuf::from)
        .expect("HOME must be set to locate the HF cache");
    home.join(".cache").join("huggingface").join("hub")
}

/// Minimal single-`*` glob: the pattern may contain exactly one `*` segment
/// (the HF `snapshots/<hash>` directory). Returns the first lexicographic
/// match. We keep this dependency-free to avoid pulling a glob crate into
/// the build.
fn first_glob_match(pattern: &Path) -> Option<PathBuf> {
    let s = pattern.to_str()?;
    let star = s.find('*')?;
    // Split into (prefix dir).../*/(suffix). The `*` sits between two `/`.
    let before = &s[..star];
    let after = &s[star + 1..];
    // `before` ends with a path separator; its parent is the dir we scan.
    let scan_dir = Path::new(before);
    let scan_dir = if before.ends_with('/') {
        scan_dir.to_path_buf()
    } else {
        scan_dir.parent()?.to_path_buf()
    };
    // `after` typically starts with "/<file>"; strip the leading separator.
    let suffix = after.strip_prefix('/').unwrap_or(after);

    let mut matches: Vec<PathBuf> = Vec::new();
    let entries = fs::read_dir(&scan_dir).ok()?;
    for entry in entries.flatten() {
        let candidate = entry.path().join(suffix);
        if candidate.is_file() {
            matches.push(candidate);
        }
    }
    matches.sort();
    matches.into_iter().next()
}

/// Resolve symlinks (HF snapshot files are symlinks into `blobs/`) so the
/// baked-in `include_bytes!` path is stable and points at real bytes.
fn canonical(path: &Path) -> PathBuf {
    fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}
